Repository TeamUltroid/Ultroid, pull requests merged in 2021-10, with the labels that each got.

#178 add Indonesian translation
  strings/strings/id.yml
Labels: hacktoberfest, hacktoberfest-accepted

#176 Added More en strings.
  strings/strings/en.yml
Labels: hacktoberfest, Translation, hacktoberfest-accepted

#179 added more id strings
  strings/strings/id.yml
Labels: Translation, hacktoberfest-accepted

#181 Update and add more Russian translations
  strings/strings/ru.yml
Labels: hacktoberfest, Translation, hacktoberfest-accepted
